name: Publish Website to CPanel (SFTP)
on:
  push:
    branches:
      - main
jobs:
  SFTP-Deploy-Action:
    name: SFTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2 
    - name: Build assets
      run: npm install && npm run build

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.2'
          tools: 'composer'

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader
        
    - name: SFTP-Deploy-Action
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        local_path: './'
        remote_path: '/public_html/'
        sftp_only: true
        delete_remote_files: false
